defaults:
  - Dataset: cifar100
  - Architecture: effnet_cifar10_std
  - Ensemble: ensemble_params
  - Quantization: qunatization_params
  - Training: training_params
params:
  data_path: ~/colab/data  # path to the training data


